### PR TITLE
Kaatje/app/forms

### PR DESCRIPTION
**Pull request by kaiye13**

### CODE REVIEW

**Comment by Joren-Thijs** [comment]
Kaatje if i run the app and i exceed my max characters on an input field instead of u subtle border the entire input field turns red.

**Comment by Joren-Thijs** [comment]
When adding an item and clicking to add a description it opens a date picker.

**Review by Joren-Thijs — CHANGES_REQUESTED** [review]
Has some bugs that need to be sorted out.

**Comment by kaiye13** [comment]
> Kaatje if i run the app and i exceed my max characters on an input field instead of u subtle border the entire input field turns red.

this would be added the a new ticket, because it normally isn't possible in the androidversion we code.

**Comment by kaiye13** [comment]
> When adding an item and clicking to add a description it opens a date picker.

just tested the app and this wasn't happening? so maybe it didn't load well, also checked the code and this should not be happening, are you sure u didn't missclick ?

**Comment by kaiye13** [comment]
> Has some bugs that need to be sorted out.

bugs have been fixes ( like the item link which did not show)

**Pull request closed without merging**
